//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Таблица1
    {
        public int Номер_абонента { get; set; }
        public string ФИО_Абонента { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> Номер_телефона { get; set; }
        public string Номер_договора { get; set; }
        public Nullable<System.DateTime> Дата_установки_телефона { get; set; }
        public Nullable<int> Номер_разговора { get; set; }
        public Nullable<System.DateTime> Дата_разговора { get; set; }
        public Nullable<System.TimeSpan> Время_разговора { get; set; }
        public Nullable<int> Код_города { get; set; }
        public string Название_города { get; set; }
        public decimal Тариф_стоимость_1мин { get; set; }
        public string Оплаты { get; set; }
    }
}
