//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Телефоны_абонентов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Телефоны_абонентов()
        {
            this.Абоненты = new HashSet<Абоненты>();
        }
    
        public int Телефоны_абонентов1 { get; set; }
        public int Код_разговора { get; set; }
        public string Номер_телефона { get; set; }
        public string Номер_договора { get; set; }
        public System.DateTime Дата_установки_телефона { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Абоненты> Абоненты { get; set; }
        public virtual Разговоры Разговоры { get; set; }
    }
}
